--- #YAML:1.0
name: Bot-BasicBot-Pluggable-Module-Network
version: 0.9
author: Simon Wistow <simon@thegestalt.org>
abstract: |-
  various network plugins for Bot::BasicBot::Pluggable
license: perl
requires:
  Bot::BasicBot::Pluggable: 0.5
  Net::Traceroute: 0
  Net::Whois: 0
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::Traceroute:
    file: lib/Bot/BasicBot/Pluggable/Module/Traceroute.pm
  Bot::BasicBot::Pluggable::Module::Whois:
    file: lib/Bot/BasicBot/Pluggable/Module/Whois.pm
generated_by: Module::Build version 0.25
